### PR TITLE
Eating simulator

### PR DESCRIPTION
**Pull request by ch1ck3n-byte**
I made this

### CODE REVIEW

**Comment by Jme7** [comment]
Thank you! this is a good addition, but I need to do some revisions, so I am merging this to eating-simulator-addition branch instead of master

**Comment by ch1ck3n-byte** [comment]
Thanks

**Comment by Jme7** [comment]
I have this addition in a branch called "eating-simulator-addition". You can keep working on it there if you want.

**Comment by Ksid6** [comment]
Hmmm, I don't know how I can help.  :(

**Comment by Jme7** [comment]
Don't worry, I was talking to @ch1ck3n-byte

**Comment by Jme7** [comment]
Ok, @ch1ck3n-byte, you can make a new branch if you need to edit this, but otherwise, this is closed

**Pull request merged**
